#######################################################
# 
# Cal_AAindex.py
# Python implementation of the Class Cal_AAindex
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Cal_AAindex:
    def cal_AAindex():
        pass