#######################################################
# 
# Cal_AAC.py
# Python implementation of the Class Cal_AAC
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Cal_AAC:
    def cal_AAC():
        pass