#######################################################
# 
# Cal_EBGW.py
# Python implementation of the Class Cal_EBGW
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Cal_EBGW:
    def cal_EBGW():
        pass