#######################################################
# 
# Cal_EBGW.py
# Python implementation of the Class Cal_EBGW
# Generated by Enterprise Architect
# Created on:      07-May-2017 18:49:59
# Original author: yum717
# 
#######################################################
import sys

class Cal_EBGW:
    def cal_EBGW():
        ctemp1 = ['G', 'A', 'V', 'L', 'I', 'M', 'P', 'F', 'W', 'Q', 'N', 'S', 'T', 'Y', 'C']
        ctemp2 = ['G', 'A', 'V', 'L', 'I', 'M', 'P', 'F', 'W', 'D', 'E']
        ctemp3 = ['G', 'A', 'V', 'L', 'I', 'M', 'P', 'F', 'W', 'H', 'K', 'R']
        N=11;
        H1 = [0 for x in range(N)]
        H2 = [0 for y in range(N)]
        H3 = [0 for z in range(N)]
        f2=open("window.txt","r")
        lines = f2.readlines()
        for line in lines:
            for i in range(0,N):
                for j in range(0,15):
                # one
                    if ((line[i] == ctemp1[j])):
                        H1[i] = 1
                print(H1[i],end='')
            
                # second
           
            for i in range(0,N):
                for j in range(0,11):
                    if ((line[i] == ctemp2[j])):
                        H2[i] = 1
                print(H2[i],end='')
            
            # third
           
            for i in range(0,N):
                for j in range (0,12):
                    if ((line[i] == ctemp3[j])):
                        H3[i] = 1
                print(H3[i],end='')
            print("\n")
out = sys.stdout
sys.stdout = open('EBGW.txt', 'w')
p = Cal_EBGW
p.cal_EBGW()
