#######################################################
# 
# Cal_PSSM.py
# Python implementation of the Class Cal_PSSM
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Cal_PSSM:
    def cal_PSSM():
        pass