#######################################################
# 
# Cal_AAindex.py
# Python implementation of the Class Cal_AAindex
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################

import sys
class Cal_AAindex:
    def cal_AAindex(self):
        L = 12
		f = open("window.txt","r")

		portein ={'A':8.1,'C':5.5,'D':13,'E':12.3,'F':5.2,'G':9,'H':10.4,'I':5.2,'K':11.3,'L':4.9,'M':5.7,'N':11.6,'P':8,'Q':10.5,'R':10.5,'S':9.2,'T':8.6,
			'V':5.9,'W':5.4,'Y':6.2}

		for negativeafter in f.readlines():
			length = len(negativeafter)
			for i in range(L-1):
		# in python2 this if-statement should be :
		# if portein.has_key(negativeafter[i]):
				if negativeafter[i] in portein:
					print(portein[negativeafter[i]],end=" ")
			print("\n",end ="")
		return 
out = sys.stdout			
sys.stdout = open("positive_Polarity.txt","w")
p = Cal_AAindex()
p.cal_AAindex()
