#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#######################################################
# 
# Cal_AAC.py
# Python implementation of the Class Cal_AAC
# Generated by Enterprise Architect
# Created on:      07-����-2017 18:49:59
# Original author: yum717
# 
#######################################################
import sys
class Cal_AAC:
    def cal_AAC(self):
        s = "ARNDCQEGHILKMFPSTWYVx"
        f = open("window.txt", "r")
        lines = f.readlines()
        for str1 in lines:
            cou = [0 for x in range(21)]
            leng = len(str1)-1
            for i in range(0,leng):
                for j in range(0,20):
                    if (str1[i] == s[j]):
                        break
                cou[j] = cou[j] + 1
            # k=1
            for k in range(0,21):
                print('%.6f'%(cou[k] / leng),end='')
            print("\n")
        return (0)


out = sys.stdout
sys.stdout = open('output.txt', 'w')
p = Cal_AAC
p.cal_AAC(p)
