#######################################################
# 
# Cal_AAC.py
# Python implementation of the Class Cal_AAC
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


import sys
class Cal_AAC:
    def cal_AAC(self):
        s="ARNDCQEGHILKMFPSTWYVx"
        f=open("window.txt","r")
        lines = f.readlines()
        for str1 in lines:
            cou = [0 for x in range(21)]
            leng=len(str1)
            for i in range(leng):
                for j in range(21):
                    if (str1[i] == s[j]):
                        break
                cou[j]=cou[j]+1
            #k=1
            for k in range(21):
                print(str(cou[k]/leng))
                fout = open("output.txt", "w")
                fout.write(str(cou[k]/leng))
        return(0)
p = Cal_AAC
p.cal_AAC(p)
