#######################################################
# 
# Control.py
# Python implementation of the Class Control
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################
import Cal_AAC
import Cal_EBGW
import Cal_AAindex
import Cal_PSSM

class Control:
    m_Cal_AAC= Cal_AAC()

    m_Cal_EBGW= Cal_EBGW()

    m_Cal_AAindex= Cal_AAindex()

    m_Cal_PSSM= Cal_PSSM()

    def Cal_feature():
        pass