#######################################################
# 
# Download_Data.py
# Python implementation of the Class Download_Data
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Download_Data:
    def download():
        pass