#######################################################
# 
# Fromat_Data.py
# Python implementation of the Class Fromat_Data
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Fromat_Data:
    def format():
        pass