#######################################################
# 
# Main.py
# Python implementation of the Class Main
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################
import Download_Data
import Fromat_Data
import Control
import Save_Biodata
import show

class Main:
    m_Download_Data= Download_Data()

    m_Fromat_Data= Fromat_Data()

    m_Control= Control()

    m_Save_Biodata= Save_Biodata()

    m_show= show()
