#######################################################
# 
# Save_Biodata.py
# Python implementation of the Class Save_Biodata
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class Save_Biodata:
    def save():
        pass