#######################################################
# 
# show.py
# Python implementation of the Class show
# Generated by Enterprise Architect
# Created on:      07-ÎåÔÂ-2017 18:49:59
# Original author: yum717
# 
#######################################################


class show:
    def show():
        pass